### ISSUE TITLE
树莓派部署项目后pq数据库出错

### ISSUE THREAD

**Issue by DemonKHH** [hetianyi/digger#3]
部署项目时报错
错误信息 pq: column "start_url" of relation "t_project" does not exist"

**Comment by hetianyi** [comment]
抱歉，树莓派版本的很久没同步发布了，今晚搞一下

**Comment by DemonKHH** [comment]
> 抱歉，树莓派版本的很久没同步发布了，今晚搞一下

辛苦大佬~

**Comment by hetianyi** [comment]
请问是什么方式部署的，docker还是二进制文件？可以尝试使用最新的数据库schema覆盖一下

**Comment by DemonKHH** [comment]
> 请问是什么方式部署的，docker还是二进制文件？可以尝试使用最新的数据库schema覆盖一下

docker部署的 我重新试一下，qq群咋进不去欸

**Comment by hetianyi** [comment]
请加微信群
